//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.LandlordDatabaseSetup.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandlordDatabaseSetupResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandlordDatabaseSetupResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.LandlordDatabaseSetup.Resources.LandlordDatabaseSetupResx" +
                            "", typeof(LandlordDatabaseSetupResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Establishing Connection..
        /// </summary>
        public static string ErrorEstablishingConnection {
            get {
                return ResourceManager.GetString("ErrorEstablishingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Processing Script..
        /// </summary>
        public static string ErrorProcessingScript {
            get {
                return ResourceManager.GetString("ErrorProcessingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Rolling Back Transaction..
        /// </summary>
        public static string ErrorRollingBackTransaction {
            get {
                return ResourceManager.GetString("ErrorRollingBackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Parameters..
        /// </summary>
        public static string InsufficientParameters {
            get {
                return ResourceManager.GetString("InsufficientParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord Database Setup..
        /// </summary>
        public static string LandlordDatabaseSetup {
            get {
                return ResourceManager.GetString("LandlordDatabaseSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Parameters..
        /// </summary>
        public static string NullParameters {
            get {
                return ResourceManager.GetString("NullParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Connection....
        /// </summary>
        public static string OpeningConnection {
            get {
                return ResourceManager.GetString("OpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Script: {0}.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-starting Worker Role Service (this may take up to a couple of minutes)....
        /// </summary>
        public static string RestartingWorkerRole {
            get {
                return ResourceManager.GetString("RestartingWorkerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Exception..
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
    }
}
