//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.MetadataDescriptions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.MetadataDescriptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file(Right click on the top and choose Edit to do paste): 
        ///.
        /// </summary>
        internal static string AdderInputPrompt {
            get {
                return ResourceManager.GetString("AdderInputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder: (Up arrow gets the input above) 
        ///.
        /// </summary>
        internal static string AdderOutputPrompt {
            get {
                return ResourceManager.GetString("AdderOutputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        internal static string DialogCaption {
            get {
                return ResourceManager.GetString("DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process {0} files. Details in {1}\.
        /// </summary>
        internal static string ErrorFailSummary {
            get {
                return ResourceManager.GetString("ErrorFailSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is not found. Please re-enter: 
        ///.
        /// </summary>
        internal static string ErrorInput {
            get {
                return ResourceManager.GetString("ErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the developers with the following information:
        ///
        ///.
        /// </summary>
        internal static string ErrorWritingFile {
            get {
                return ResourceManager.GetString("ErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} has wrong format in the input file!.
        /// </summary>
        internal static string ErrorWrongFormat {
            get {
                return ResourceManager.GetString("ErrorWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} failed
        ///{1}.
        /// </summary>
        internal static string ExpectionLogInfo {
            get {
                return ResourceManager.GetString("ExpectionLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input folder(Right click on the top and choose Edit to do paste):
        ///.
        /// </summary>
        internal static string ExtractorInputPrompt {
            get {
                return ResourceManager.GetString("ExtractorInputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file: (Up arrow gets the input above)
        ///.
        /// </summary>
        internal static string ExtractorOutputPrompt {
            get {
                return ResourceManager.GetString("ExtractorOutputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed..
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} failed.
        /// </summary>
        internal static string FailLogInfo {
            get {
                return ResourceManager.GetString("FailLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} .htm files to be processed..
        /// </summary>
        internal static string FileProcessSummary {
            get {
                return ResourceManager.GetString("FileProcessSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the Description!.
        /// </summary>
        internal static string GetDescription {
            get {
                return ResourceManager.GetString("GetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.txt.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished the description insertion to the output files!.
        /// </summary>
        internal static string PromptAdderFinish {
            get {
                return ResourceManager.GetString("PromptAdderFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in any key to continue...
        /// </summary>
        internal static string PromptContinue {
            get {
                return ResourceManager.GetString("PromptContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in any key to exit...
        /// </summary>
        internal static string PromptExit {
            get {
                return ResourceManager.GetString("PromptExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished writing description to the output file!.
        /// </summary>
        internal static string PromptExtractorFinish {
            get {
                return ResourceManager.GetString("PromptExtractorFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succeeded. Insert the Description!.
        /// </summary>
        internal static string PromptInsert {
            get {
                return ResourceManager.GetString("PromptInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} Processing description in {2} .
        /// </summary>
        internal static string PromptProcessing {
            get {
                return ResourceManager.GetString("PromptProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to retry?(Y/N).
        /// </summary>
        internal static string PromptRetry {
            get {
                return ResourceManager.GetString("PromptRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose 1/2:
        ///(1)Extract description       (2)Add description.
        /// </summary>
        internal static string PromptToolChoose {
            get {
                return ResourceManager.GetString("PromptToolChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Choice, Retry.
        /// </summary>
        internal static string PromptWrongChoice {
            get {
                return ResourceManager.GetString("PromptWrongChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succeeded..
        /// </summary>
        internal static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File Path,Output File Path,File Name,Topic Class,Meta Description.
        /// </summary>
        internal static string TitleLine {
            get {
                return ResourceManager.GetString("TitleLine", resourceCulture);
            }
        }
    }
}
