//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA.TU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPA.TU.Resources.MenuResx", typeof(MenuResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPA.
        /// </summary>
        public static string TPA {
            get {
                return ResourceManager.GetString("TPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Group.
        /// </summary>
        public static string TU_Account_Group {
            get {
                return ResourceManager.GetString("TU_Account_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Group 1.
        /// </summary>
        public static string TU_Account_Group_1 {
            get {
                return ResourceManager.GetString("TU_Account_Group_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Group 2.
        /// </summary>
        public static string TU_Account_Group_2 {
            get {
                return ResourceManager.GetString("TU_Account_Group_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Set.
        /// </summary>
        public static string TU_Account_Set {
            get {
                return ResourceManager.GetString("TU_Account_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Set 1.
        /// </summary>
        public static string TU_Account_Set_1 {
            get {
                return ResourceManager.GetString("TU_Account_Set_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Set 2.
        /// </summary>
        public static string TU_Account_Set_2 {
            get {
                return ResourceManager.GetString("TU_Account_Set_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Set Group 1.
        /// </summary>
        public static string TU_Account_Set_Group_1 {
            get {
                return ResourceManager.GetString("TU_Account_Set_Group_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Set Group 2.
        /// </summary>
        public static string TU_Account_Set_Group_2 {
            get {
                return ResourceManager.GetString("TU_Account_Set_Group_2", resourceCulture);
            }
        }
    }
}
