//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA.TU.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountGroupsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountGroupsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPA.TU.Resources.Forms.AccountGroupsResx", typeof(AccountGroupsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU  Account Group.
        /// </summary>
        public static string AccountGroup {
            get {
                return ResourceManager.GetString("AccountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU  Account Group Code.
        /// </summary>
        public static string AccountGroupCode {
            get {
                return ResourceManager.GetString("AccountGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU  Account Group Description.
        /// </summary>
        public static string AccountGroupDesc {
            get {
                return ResourceManager.GetString("AccountGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Groups.
        /// </summary>
        public static string AP0006 {
            get {
                return ResourceManager.GetString("AP0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Currency Code for Account.
        /// </summary>
        public static string CurrencyCodeForAcct {
            get {
                return ResourceManager.GetString("CurrencyCodeForAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Discounts Account.
        /// </summary>
        public static string DiscountsAcct {
            get {
                return ResourceManager.GetString("DiscountsAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Distribution Code.
        /// </summary>
        public static string DistributionCode {
            get {
                return ResourceManager.GetString("DistributionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Groups.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Exchange Rounding.
        /// </summary>
        public static string ExchRounding {
            get {
                return ResourceManager.GetString("ExchRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Exchange Rounding Account.
        /// </summary>
        public static string ExchRoundingAcct {
            get {
                return ResourceManager.GetString("ExchRoundingAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU G/L Account.
        /// </summary>
        public static string GenLedgerAcct {
            get {
                return ResourceManager.GetString("GenLedgerAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Account Description.
        /// </summary>
        public static string GenLedgerAcctDesc {
            get {
                return ResourceManager.GetString("GenLedgerAcctDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Inactive Date.
        /// </summary>
        public static string InactiveDate {
            get {
                return ResourceManager.GetString("InactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Payables Control.
        /// </summary>
        public static string PayablesControl {
            get {
                return ResourceManager.GetString("PayablesControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Payables Control Account.
        /// </summary>
        public static string PayablesControlAcct {
            get {
                return ResourceManager.GetString("PayablesControlAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Prepayment.
        /// </summary>
        public static string Prepayment {
            get {
                return ResourceManager.GetString("Prepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Prepayment Account.
        /// </summary>
        public static string PrepaymentAcct {
            get {
                return ResourceManager.GetString("PrepaymentAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Purchase Discounts.
        /// </summary>
        public static string PurchaseDiscounts {
            get {
                return ResourceManager.GetString("PurchaseDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Retainage.
        /// </summary>
        public static string Retainage {
            get {
                return ResourceManager.GetString("Retainage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Retainage Account.
        /// </summary>
        public static string RetainageAcct {
            get {
                return ResourceManager.GetString("RetainageAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Exchange Gain.
        /// </summary>
        public static string RlzExchGain {
            get {
                return ResourceManager.GetString("RlzExchGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Exchange Gain Account.
        /// </summary>
        public static string RlzExchGainAcct {
            get {
                return ResourceManager.GetString("RlzExchGainAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Exchange Loss.
        /// </summary>
        public static string RlzEXchLoss {
            get {
                return ResourceManager.GetString("RlzEXchLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Exchange Loss Account.
        /// </summary>
        public static string RlzExchLossAcct {
            get {
                return ResourceManager.GetString("RlzExchLossAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Unrealized Exchange Gain.
        /// </summary>
        public static string UnrlzExchGain {
            get {
                return ResourceManager.GetString("UnrlzExchGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Unrealized Exchange Gain Account.
        /// </summary>
        public static string UnrlzExchGainAcct {
            get {
                return ResourceManager.GetString("UnrlzExchGainAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Unrealized Exchange Loss.
        /// </summary>
        public static string UnrlzExchLoss {
            get {
                return ResourceManager.GetString("UnrlzExchLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU Unrealized Exchange Loss Account.
        /// </summary>
        public static string UnrlzExchLossAcct {
            get {
                return ResourceManager.GetString("UnrlzExchLossAcct", resourceCulture);
            }
        }
    }
}
