//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DrillDownResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DrillDownResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.Common.Resources.DrillDownResx", typeof(DrillDownResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AP/InvoiceEntry?batchNumber={0}&amp;entryNumber={1}&amp;actionType={2}.
        /// </summary>
        public static string AP2100 {
            get {
                return ResourceManager.GetString("AP2100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AP/PaymentEntry?batchNo={0}&amp;entryNo={1}&amp;FromScreen={2}.
        /// </summary>
        public static string AP3100 {
            get {
                return ResourceManager.GetString("AP3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AP/AdjustmentEntry?batchNo={0}&amp;entryNo={1}&amp;actionType={2}.
        /// </summary>
        public static string AP4100 {
            get {
                return ResourceManager.GetString("AP4100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AR/InvoiceEntry?batchNumber={0}&amp;entryNumber={1}&amp;actionType={2}.
        /// </summary>
        public static string AR2100 {
            get {
                return ResourceManager.GetString("AR2100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AR/ReceiptEntry?batchNumber={0}&amp;entryNumber={1}&amp;actionType={2}.
        /// </summary>
        public static string AR3100 {
            get {
                return ResourceManager.GetString("AR3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AR/AdjustmentEntry?batchNumber={0}&amp;entryNumber={1}&amp;actionType={2}.
        /// </summary>
        public static string AR4100 {
            get {
                return ResourceManager.GetString("AR4100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AR/RefundEntry?batchNumber={0}&amp;entryNumber={1}&amp;actionType={2}.
        /// </summary>
        public static string AR5020 {
            get {
                return ResourceManager.GetString("AR5020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CS/BankTransfer?postSequence={0}&amp;keySequence={1}&amp;sequenceType={2}.
        /// </summary>
        public static string BK2050 {
            get {
                return ResourceManager.GetString("BK2050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CS/BankEntry?sequenceNumber={0}.
        /// </summary>
        public static string BK2300 {
            get {
                return ResourceManager.GetString("BK2300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CS/ReconcileStatement?postSequence={0}&amp;bankSequence={1}&amp;sequenceType={2}.
        /// </summary>
        public static string BK6000 {
            get {
                return ResourceManager.GetString("BK6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IC/Receipt?id={0}&amp;disableAll={1}.
        /// </summary>
        public static string IC3120 {
            get {
                return ResourceManager.GetString("IC3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IC/Shipment?id={0}&amp;integratedScreen={1}.
        /// </summary>
        public static string IC3210 {
            get {
                return ResourceManager.GetString("IC3210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IC/Adjustment?id={0}&amp;integratedScreen={1}.
        /// </summary>
        public static string IC3310 {
            get {
                return ResourceManager.GetString("IC3310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IC/Transfer?id={0}&amp;isEditable={1}.
        /// </summary>
        public static string IC3410 {
            get {
                return ResourceManager.GetString("IC3410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /IC/InternalUsage?id={0}&amp;disableAll={1}.
        /// </summary>
        public static string IC3530 {
            get {
                return ResourceManager.GetString("IC3530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /OE/CreditDebitNoteEntry?drillDownkey={0}&amp;disableAll={1}.
        /// </summary>
        public static string OE1600 {
            get {
                return ResourceManager.GetString("OE1600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /OE/ShipmentEntry?drillDownKey={0}&amp;isEditable={1}.
        /// </summary>
        public static string OE2200 {
            get {
                return ResourceManager.GetString("OE2200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PO/ReceiptEntry?sequenceKey={0}&amp;isNavigated={1}.
        /// </summary>
        public static string PO1310 {
            get {
                return ResourceManager.GetString("PO1310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PO/ReturnEntry?sequenceKey={0}&amp;disableAll={1}.
        /// </summary>
        public static string PO1320 {
            get {
                return ResourceManager.GetString("PO1320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PO/InvoiceEntry?invoiceSequence={0}&amp;isDisable={1}.
        /// </summary>
        public static string PO1400 {
            get {
                return ResourceManager.GetString("PO1400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PO/CreditDebitNoteEntry?sequenceKey={0}&amp;disable={1}.
        /// </summary>
        public static string PO1500 {
            get {
                return ResourceManager.GetString("PO1500", resourceCulture);
            }
        }
    }
}
