//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumerationsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumerationsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.Common.Resources.EnumerationsResx", typeof(EnumerationsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Posted.
        /// </summary>
        public static string AdjustmentPosted {
            get {
                return ResourceManager.GetString("AdjustmentPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Express.
        /// </summary>
        public static string AmericanExpress {
            get {
                return ResourceManager.GetString("AmericanExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        public static string Captured {
            get {
                return ResourceManager.GetString("Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Pending.
        /// </summary>
        public static string CapturePending {
            get {
                return ResourceManager.GetString("CapturePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Declined.
        /// </summary>
        public static string CardDeclined {
            get {
                return ResourceManager.GetString("CardDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Error.
        /// </summary>
        public static string CardError {
            get {
                return ResourceManager.GetString("CardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note Summary Entered.
        /// </summary>
        public static string CreditNoteSummaryEntered {
            get {
                return ResourceManager.GetString("CreditNoteSummaryEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string Csv {
            get {
                return ResourceManager.GetString("Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day End Processing.
        /// </summary>
        public static string DayEndProcessing {
            get {
                return ResourceManager.GetString("DayEndProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Card.
        /// </summary>
        public static string DebitCard {
            get {
                return ResourceManager.GetString("DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Note Advance Credit Claim.
        /// </summary>
        public static string DebitNoteAdvanceCreditClaim {
            get {
                return ResourceManager.GetString("DebitNoteAdvanceCreditClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Note Summary Entered.
        /// </summary>
        public static string DebitNoteSummaryEntered {
            get {
                return ResourceManager.GetString("DebitNoteSummaryEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        public static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During Posting.
        /// </summary>
        public static string DuringPosting {
            get {
                return ResourceManager.GetString("DuringPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string EntityError_Priority_Error {
            get {
                return ResourceManager.GetString("EntityError_Priority_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string EntityError_Priority_Message {
            get {
                return ResourceManager.GetString("EntityError_Priority_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string EntityError_Priority_Security {
            get {
                return ResourceManager.GetString("EntityError_Priority_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe Error.
        /// </summary>
        public static string EntityError_Priority_SevereError {
            get {
                return ResourceManager.GetString("EntityError_Priority_SevereError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string EntityError_Priority_Warning {
            get {
                return ResourceManager.GetString("EntityError_Priority_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO.
        /// </summary>
        public static string FIFO {
            get {
                return ResourceManager.GetString("FIFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Set.
        /// </summary>
        public static string FinderType_AccountSet {
            get {
                return ResourceManager.GetString("FinderType_AccountSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number Code.
        /// </summary>
        public static string FinderType_BatchNumberCode {
            get {
                return ResourceManager.GetString("FinderType_BatchNumberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Set.
        /// </summary>
        public static string FinderType_DistributionSet {
            get {
                return ResourceManager.GetString("FinderType_DistributionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Journal Profile.
        /// </summary>
        public static string FinderType_SourceJournalProfile {
            get {
                return ResourceManager.GetString("FinderType_SourceJournalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Ledger Code.
        /// </summary>
        public static string FinderType_SourceLedgerCode {
            get {
                return ResourceManager.GetString("FinderType_SourceLedgerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Code.
        /// </summary>
        public static string FinderType_TermsCode {
            get {
                return ResourceManager.GetString("FinderType_TermsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional.
        /// </summary>
        public static string Functional {
            get {
                return ResourceManager.GetString("Functional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get default card&apos;s processing code, bank, and currency.
        /// </summary>
        public static string GetdefaultcardsprocessingcodebankAndcurrency {
            get {
                return ResourceManager.GetString("GetdefaultcardsprocessingcodebankAndcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get default processing code.
        /// </summary>
        public static string Getdefaultprocessingcode {
            get {
                return ResourceManager.GetString("Getdefaultprocessingcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Replace.
        /// </summary>
        public static string InsertReplace {
            get {
                return ResourceManager.GetString("InsertReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Update.
        /// </summary>
        public static string InsertUpdate {
            get {
                return ResourceManager.GetString("InsertUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Charge.
        /// </summary>
        public static string InterestCharge {
            get {
                return ResourceManager.GetString("InterestCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Recurring Charge.
        /// </summary>
        public static string InvoiceRecurringCharge {
            get {
                return ResourceManager.GetString("InvoiceRecurringCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Summary Entered.
        /// </summary>
        public static string InvoiceSummaryEntered {
            get {
                return ResourceManager.GetString("InvoiceSummaryEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCB.
        /// </summary>
        public static string JCB {
            get {
                return ResourceManager.GetString("JCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian.
        /// </summary>
        public static string Language_Australian {
            get {
                return ResourceManager.GetString("Language_Australian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        public static string Language_ChnSimple {
            get {
                return ResourceManager.GetString("Language_ChnSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        public static string Language_ChnTrad {
            get {
                return ResourceManager.GetString("Language_ChnTrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_Eng {
            get {
                return ResourceManager.GetString("Language_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican.
        /// </summary>
        public static string Language_Mexican {
            get {
                return ResourceManager.GetString("Language_Mexican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFO.
        /// </summary>
        public static string LIFO {
            get {
                return ResourceManager.GetString("LIFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Batch Resource Exclusive.
        /// </summary>
        public static string LockBatchResourceExclusive {
            get {
                return ResourceManager.GetString("LockBatchResourceExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Batch Resource Shared.
        /// </summary>
        public static string LockBatchResourceShared {
            get {
                return ResourceManager.GetString("LockBatchResourceShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master card.
        /// </summary>
        public static string MasterCard {
            get {
                return ResourceManager.GetString("MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent Cost.
        /// </summary>
        public static string MostRecentCost {
            get {
                return ResourceManager.GetString("MostRecentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Average.
        /// </summary>
        public static string MovingAverage {
            get {
                return ResourceManager.GetString("MovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No / N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Proration.
        /// </summary>
        public static string NoProration {
            get {
                return ResourceManager.GetString("NoProration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Request Using Create G/L Batch Screen.
        /// </summary>
        public static string OnRequestGLBatch {
            get {
                return ResourceManager.GetString("OnRequestGLBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Posted.
        /// </summary>
        public static string PaymentPosted {
            get {
                return ResourceManager.GetString("PaymentPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting.
        /// </summary>
        public static string Posting {
            get {
                return ResourceManager.GetString("Posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-auth Pending.
        /// </summary>
        public static string PreauthPending {
            get {
                return ResourceManager.GetString("PreauthPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Posted.
        /// </summary>
        public static string PrepaymentPosted {
            get {
                return ResourceManager.GetString("PrepaymentPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGA.
        /// </summary>
        public static string Product_Cga {
            get {
                return ResourceManager.GetString("Product_Cga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string Product_Corporate {
            get {
                return ResourceManager.GetString("Product_Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        public static string Product_Discovery {
            get {
                return ResourceManager.GetString("Product_Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise.
        /// </summary>
        public static string Product_Enterprise {
            get {
                return ResourceManager.GetString("Product_Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Business.
        /// </summary>
        public static string Product_SmallBusiness {
            get {
                return ResourceManager.GetString("Product_SmallBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate.
        /// </summary>
        public static string Prorate {
            get {
                return ResourceManager.GetString("Prorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate by Cost.
        /// </summary>
        public static string ProratebyCost {
            get {
                return ResourceManager.GetString("ProratebyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate by Quantity.
        /// </summary>
        public static string ProratebyQuantity {
            get {
                return ResourceManager.GetString("ProratebyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate by Weight.
        /// </summary>
        public static string ProratebyWeight {
            get {
                return ResourceManager.GetString("ProratebyWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate Manually.
        /// </summary>
        public static string ProrateManually {
            get {
                return ResourceManager.GetString("ProrateManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        public static string RateOperator_Divide {
            get {
                return ResourceManager.GetString("RateOperator_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string RateOperator_Multiply {
            get {
                return ResourceManager.GetString("RateOperator_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revaluation.
        /// </summary>
        public static string Revaluation {
            get {
                return ResourceManager.GetString("Revaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revaluation Date.
        /// </summary>
        public static string RevaluationDate {
            get {
                return ResourceManager.GetString("RevaluationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revaluation Method.
        /// </summary>
        public static string RevaluationMethod {
            get {
                return ResourceManager.GetString("RevaluationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized and Unrealized Gain/Loss Revaluation.
        /// </summary>
        public static string RevaluationMethod_RealizedAndUnrealizedGainLossRevaluation {
            get {
                return ResourceManager.GetString("RevaluationMethod_RealizedAndUnrealizedGainLossRevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized Gain/Loss Revaluation.
        /// </summary>
        public static string RevaluationMethod_RecognizedGainLossRevaluation {
            get {
                return ResourceManager.GetString("RevaluationMethod_RecognizedGainLossRevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SecurityType_Add {
            get {
                return ResourceManager.GetString("SecurityType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SecurityType_Delete {
            get {
                return ResourceManager.GetString("SecurityType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquire.
        /// </summary>
        public static string SecurityType_Inquire {
            get {
                return ResourceManager.GetString("SecurityType_Inquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string SecurityType_Modify {
            get {
                return ResourceManager.GetString("SecurityType_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SecurityType_None {
            get {
                return ResourceManager.GetString("SecurityType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string SecurityType_Post {
            get {
                return ResourceManager.GetString("SecurityType_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Cost.
        /// </summary>
        public static string StandardCost {
            get {
                return ResourceManager.GetString("StandardCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string SymbolSpace {
            get {
                return ResourceManager.GetString("SymbolSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical.
        /// </summary>
        public static string Type_Logical {
            get {
                return ResourceManager.GetString("Type_Logical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        public static string Type_Physical {
            get {
                return ResourceManager.GetString("Type_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Batch Resource.
        /// </summary>
        public static string UnlockBatchResource {
            get {
                return ResourceManager.GetString("UnlockBatchResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Specified.
        /// </summary>
        public static string UserSpecified {
            get {
                return ResourceManager.GetString("UserSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 1.
        /// </summary>
        public static string Vendor1 {
            get {
                return ResourceManager.GetString("Vendor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 2.
        /// </summary>
        public static string Vendor2 {
            get {
                return ResourceManager.GetString("Vendor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 3.
        /// </summary>
        public static string Vendor3 {
            get {
                return ResourceManager.GetString("Vendor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 4.
        /// </summary>
        public static string Vendor4 {
            get {
                return ResourceManager.GetString("Vendor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 5.
        /// </summary>
        public static string Vendor5 {
            get {
                return ResourceManager.GetString("Vendor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 6.
        /// </summary>
        public static string Vendor6 {
            get {
                return ResourceManager.GetString("Vendor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 7.
        /// </summary>
        public static string Vendor7 {
            get {
                return ResourceManager.GetString("Vendor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 8.
        /// </summary>
        public static string Vendor8 {
            get {
                return ResourceManager.GetString("Vendor8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor 9.
        /// </summary>
        public static string Vendor9 {
            get {
                return ResourceManager.GetString("Vendor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voided.
        /// </summary>
        public static string Voided {
            get {
                return ResourceManager.GetString("Voided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Pending.
        /// </summary>
        public static string VoidPending {
            get {
                return ResourceManager.GetString("VoidPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year and Period.
        /// </summary>
        public static string YearAndPeriod {
            get {
                return ResourceManager.GetString("YearAndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
